version: "3.8"

volumes:
  postgres-data:

networks:
  elib-network:

services:
  eLib:
    image: elib
    build:
      context: src/api
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - postgres
    networks:
      - elib-network

  web:
    image: elib-web
    build:
      context: src/web/eLib
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - elib-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: elib
      POSTGRES_PASSWORD: elib
      POSTGRES_DB: elib
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - elib-network