version: "3.8"

networks:
  elib-network:

services:
  eLib:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    image: eLibCR.azurecr.io/elib:latest
    container_name: elib-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
    ports:
      - "3000:8080"
    networks:
      - elib-network

  elib-Notification.Service:
    build:
      context: ./src/eLib.NotificationService
      dockerfile: Dockerfile
    image: eLibCR.azurecr.io/elib-notification:latest
    container_name: elib-notification-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
    ports:
      - "3001:8080"
    networks:
      - elib-network

  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    image: eLibCR.azurecr.io/elib-web:latest
    container_name: elib-front
    ports:
      - "80:3000"
    networks:
      - elib-network
