version: "3.8"

volumes:
  postgres-data:

services:
  eLib:
    image: elib
    build:
      context: src/api
      dockerfile: Dockerfile
    ports:
      - "3000:8080"

  web:
    image: elib-web
    build:
      context: src/web/eLib
      dockerfile: Dockerfile
    ports:
      - "80:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: elib
      POSTGRES_PASSWORD: elib
      POSTGRES_DB: elib
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

